project_id = "hzcorwgktaaxxiggzyby"

[functions.generate-guia-clase]
verify_jwt = false

[functions.generate-quiz-pre]
verify_jwt = false

[functions.generate-quiz-post]
verify_jwt = false

[functions.generate-recomendaciones]
verify_jwt = false

[functions.generate-desempenos]
verify_jwt = false
